name: 'template_expressions'
description: 'A Dart library to process string based templates using expressions.'
homepage: 'https://github.com/peiffer-innovations/template_expressions'
version: '3.2.0+7'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: '^3.1.1'
  crypto: '^3.0.1'
  encrypt: '^5.0.3'
  fake_async: '^1.3.0'
  intl: '^0.19.0'
  json_class: '^3.0.0+13'
  json_path: '>=0.6.3 <1.0.0'
  logging: '^1.2.0'
  meta: '^1.12.0'
  petitparser: '^6.0.1'
  pointycastle: '^3.9.1'
  quiver: '^3.2.1'
  rxdart: '^0.27.7'
  yaon: '^1.1.4+10'

dev_dependencies:
  flutter_lints: '^4.0.0'
  test: '^1.25.5'

permittedLicenses:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - MIT
  - MIT-Modern-Variant
  - MPL-2.0
  - Zlib

# The [license_checker](https://pub.dev/packages/license_checker) package cannot
# detect the built in Flutter packages because they aren't published to pub.dev
# and do not have a LICENSE file in their respective folders.  So this section
# informs the license_checker that all the built in Flutter packages all have
# the same BSD-3-Clause license as Flutter itself. 
packageLicenseOverride: 
  flutter: BSD-3-Clause
  flutter_driver: BSD-3-Clause
  flutter_goldens: BSD-3-Clause
  flutter_localizations: BSD-3-Clause
  flutter_web_plugins: BSD-3-Clause
  flutter_test: BSD-3-Clause
  fuchsia_remote_debug_protocol: BSD-3-Clause
  integration_test: BSD-3-Clause
  rxdart: Apache-2.0

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'json_path'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'petitparser'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
