name: 'template_expressions'
description: 'A Dart library to process string based templates using expressions.'
homepage: 'https://github.com/peiffer-innovations/template_expressions'
version: '3.1.5+1'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  convert: '^3.1.1'
  crypto: '^3.0.1'
  encrypt: '^5.0.3'
  fake_async: '^1.3.0'
  intl: '^0.19.0'
  json_class: '^3.0.0+9'
  json_path: '^0.6.3'
  logging: '^1.2.0'
  meta: '^1.10.0'
  petitparser: '^6.0.1'
  pointycastle: '^3.7.3'
  quiver: '^3.2.1'
  rxdart: '^0.27.7'
  yaon: '^1.1.4'

dev_dependencies: 
  flutter_lints: '^3.0.1'
  test: '^1.24.9'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'json_path'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'petitparser'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
